name: Update VSCode Extensions

on:
  schedule:
    # Runs once a week on Sunday at midnight (00:00 UTC)
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual triggering from GitHub interface.

jobs:
  update-extensions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install VSCode
      run: sudo apt-get install -y code

    - name: Append Extensions to README.md
      run: |
        code --list-extensions > extensions.txt
        
        # Clear previous extensions section in README.md if it exists
        sed -i '/# My VSCode Extensions/,$d' README.md
        
        # Append the extensions list to README.md
        echo "" >> README.md
        echo "# My VSCode Extensions" >> README.md
        echo "" >> README.md
        echo "| Extension Name | Publisher |" >> README.md
        echo "| -------------- | --------- |" >> README.md
        while IFS= read -r extension; do
          extensionName=$(echo "$extension" | awk -F '.' '{print $2}')
          publisher=$(echo "$extension" | awk -F '.' '{print $1}')
          echo "| $extensionName | $publisher |" >> README.md
        done < extensions.txt

    - name: Commit and push updated README.md
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Auto-update VSCode extensions list"
        git push

